### ISSUE TITLE
Eine Methode in Actions, welche vorraussagt ob diese gelingen wird

### ISSUE THREAD

**Issue by kaimuell** [ss22-fp-mapc-gruppe6/agent#26]
Eine Methode, definiert in G6Action, welche die aktuellen Gegebenheiten abgleicht um vorherzusagen ob diese Action erfolgreich sein wird.

Vorschlag : 

boolean predictSuccess(PerceptionAndMemory perceptionAndMemory)

Beispiel:

Für Move. Abgleich der Geschwindigkeit mit den Rollen des Agenten. Die Strecke auf dem Weg auf Hindernisse, Blöcke und evtl. andere Agenten checken. Wenn Blockiert -> false, sonst -> true.

Für Rotate. Abgleich der getragenen Blöcke mit Hindernissen und Agenten (Nicht Blöcke!) im Weg. Falls Blockiert -> true, sonst ->false.

Bitte mit UnitTests.

**Comment by kaimuell** [comment]
Dies soll dazu dienen die Nebenbedingungen für den Erfolg einer Action an einem Punkt zu sammeln um es dort optimieren zu können.

**Comment by kaimuell** [comment]
Objekt-Orientiert richtiger währe eine Predictor Klasse zu bauen in welcher diese vorbedingungen für jede Action bestimmt werden und diese die Entscheidung übernehmen zu lassen. Dies wäre auch eine Möglichkeit.

Es in der entsprechenden Action zu haben, bietet jedoch die Möglichkeit eine Liste möglicher Actions zu bauen und diese einfach durch das aufrufen der Methode danach zu filtern ob die mögliche Action erfolgriech sein wird.

**Comment by kaimuell** [comment]
Habe nur bei der Implementierung der Goals gemerkt, dass es mühselig war die ganzen Nebenbedingungen für eine Action abzufragen und wenn man dann den Grund gefunden hat warum etwas nicht funktioniert, es in allen Goals zu ändern. Auch machte das Abfragen der Nebenbedingungen den Code auch ziemlich unleserlich (abgesehen davon dass die aktuellen Goals eh Code von Müllqualität haben, aber irgendwie funktionieren). Dachte dies damit auffangen zu können. 

Vielleicht hast du aber auch recht und wenn wir eine Wegfindung haben, welche sich zumindest darum kümmert wenn der Agent sich von A nach B bewegen will, wird es vielleicht auch so beherrschbar. Es ist aber schon hart, immer an alles zu denken.

**Comment by mpnsk** [comment]
Ich habe noch mehr darüber nachgedacht. Im Wegfindungsalgorithmus müssen diese Nebenbedingung natürlich auch geprüft und wie du sagst das macht es schwieriger den High-Level Gedanken des codes zu schreiben und später auch wieder zu lesen. Es sei denn ich lager das ganze in eigene Methoden aus und in dem Moment kann man das auch einmal sauber und zentral in den Actions machen.
Ich bin mir nicht ganz sicher aber ich glaube auch tatsächlich dass das mit den Exceptions eine gute Idee sein könnte. Wenn zB G6Action die methode `boolean predictSuccess(PerceptionAndMemory perceptionAndMemory) throws Exception` bekommt und Move das als `boolean predictSuccess(PerceptionAndMemory perceptionAndMemory) throws AttachmentCaughtInObstacleException` implementiert würde das ja (aber nur wenn ich das mit `predictSuccess` fordere) direkt auf der Typebene meinen code zwingen den edgecase zu beachten. In etwa so:
```java
//consider all directions
for(Direction d : Direction.values()){
    Move move = new Move(d);
    try {
        move.predictSuccess(perceptionAndMemory);
    } catch (AttachmentCaughtInObstacleException e) {
        //got caught, get position of problem attachment, try to rotate
        Block block = e.getCausingAttachment();
        //determine whether to dodge obstacle by turning cw or ccw
        Rotation r = calculateRotationDirection(move, block);
        //implementation is left as an exercise for the reader :^)
    }
}
```
`getCausingAttachment()` kann dabei eine Methode sein die die Exception implementiert um bei der Problemlösung zu helfen.

Gefällt mir erstmal ganz gut. 
Das einizge was mich da im Moment stört ist das man in hypothetischen Situationen das PerceptionAndMemory verändern/kopieren muss. Ich glaube aber das könnte mit Lomboks `@With` gut gehen https://projectlombok.org/features/With 
Ich wollte Lombok eh als Abhängigkeit haben und hab bis jetzt nur den Vorwand gebraucht! :D

Ich probier das mal aus und sag heute nachmittag ob das hinderlich ist oder nicht.

**Comment by mpnsk** [comment]
okay, ich kann schon mal sagen wenn wir `PerceptionAndMemory` als Argument wollen dann sollte das eine dumme Pojo Klasse ein Record oder sowas werden.
Ich hänge daran das PerceptionAndMemory die attachedBlocks aus dem modul berechnet und das kann auch nicht einfach konstruiert werden sondern will LastActionMemorys. Das macht das ganze ziemlich umständlich und ich weiß nicht an welcher Stelle ich es mit dem geringsten Schaden verbiegen kann

**Comment by kaimuell** [comment]
Habe auch nochmal darüber nachgedacht. Und wenn andere Zustände als der ist Zustand betrachtet werden, dann ist PerceptionAndMemory zu übergeben wohl wirklich fast unmöglich. Das Ding ist einfach  zu komplex. Da macht eine Signatur wie von dir vorgeschlagen auf jeden Fall mehr Sinn.  Dadurch wird es zwar nichts mehr die Methode in dem G6Action Interface für alle Klassen zu definieren, aber für die meisten brauchen wir es ja wohl auch nicht. 

Bzw. ist ja eigentlich auch kein Problem zwei Methoden mit dem selben Namen und unterschiedlichen Signaturen zu haben. Also eine 

public boolean predictSuccess(PerceptionAndMemory perceptionAndMemory)

welche nichts anderes tut, als die Listen rauszunehmen und

public boolean predictSuccess(List<Point> attachments, List<Point> obstacles)

aufzurufen.


So hätte man eine spezielle (zugeschnitten auf genau diese Action) und allgemeine Methode welche für alle Actions gilt.

**Comment by kaimuell** [comment]
Vorerst abgeschlossen.
