### ISSUE TITLE
AttachedBlocksModule vervollständigen

### ISSUE THREAD

**Issue by kaimuell** [ss22-fp-mapc-gruppe6/agent#43]
Es fehlen noch die cases für connect und disconnect, was die Kommunikation zwicshen den Agenten erfordert.

Sowie eventuell die Möglichkeit zu kommunizieren wenn eine Attach-Action einen anderen Agenten involviert, beispielsweise wenn sich an den anderen Agenten attached wird.

**Comment by kaimuell** [comment]
Das AttachedBlocksModule tracked, welche Blocks an den Agenten attached sind. Dazu implementiert es das Interface LastActionListener und wird von der PerceptionAndMemoryImplementation über die Action der letzten Runde benachrichtigt. Jeder Agent ist also dafür verantwortlich Buch zu führen, welche Blöcke er trägt. Dies ist nötig, da die Percepts nur sagen ob eine Entität an einer relativen Koordinate an irgendetwas attached ist. Diese Percepts direkt zu nutzen führt dann zu vielen Problemen, beispielsweise wenn 2 Agenten nebeneinanderstehen.

Für connect und disconnect bebnötigt das tracken jedoch ein benachrichtigen des anderen Agenten(dessen Name über die Parameter der Aktion spezifiziert ist), da die Blöcke an diesem verändert werden. Der andere Agent muss folglich seine attachten Blöcke anpassen.

Folglich benötigt das AttachedBlocksModule Zugang zum CommunicationModule (am besten durch Dependency-Injection und gleichzeitiges anmelden am Communication Module) und benötigt Methoden um entsprechende Nachrichten zu verschicken und diese zu verarbeiten. Die Nachrichrten müssen natürlich noch definiert werden. Die bereits vergebenen Nachrichten-Namen sind im documentation Ordner unter message_documentation zu finden.

Ausserdem muss im CommunicationModule definiert werden, dass eine entsprechende Nachricht an das Attached Blocks Module weitergeleitet werden. 


Das mit der Attach-Action und anderen Agenten ist höchstens etwas für längerfristig. Hier ist es so, dass wenn ein Agent einen Block attached, an welchen auch ein anderer Agent attached ist alle seine attachments auch für diesen Agenten als attached gelten...

**Comment by kaimuell** [comment]
Erstes Code Review (18.07.):

Um das CommunicationModule im Konstruktor zu übergeben müsste PerceptionAndMemory dieses kennen, Eine dependency injection für das Modul wäre besser, dabei kann man dann auch das Modul im CommunicationModule anmelden (am besten im PerceptionAndMemoryLinker vornhmen). Dieses muss das Modul ja auch kennen um ihm nachrichten weiterleiten zu können.

Zeile 49 : default ->System.out.println("Error. Name of lastAction does not exist."); 
Macht keinen Sinn, da es ja auch viele Actions gibt, die nichts mit Blocks zu tun haben und für die sich das Modul einfach nicht interessiert.

Zeile 132 und folgende.
Die Parameter in der ParameterListe hängen von den Actions ab und etsprechen dennen welche im Konstruktor der eis.ilang.Action (Also in den G6Actions in super() ) übergeben werden.
Also beispielsweise Connect 
[0] : (identifier) otherAgentsName
[1] : (Numeral) blockPosition.x
[2] (Numeral) blockPosition.y

entsprechend dann auch für diconnect und seine Parameter

folglich macht auch die andere Logik die Blocks zu bestimmen keinen Sinn. Diese sind ja durch die Parameter der Action bestimmt und wir wissen das sie erfolgreich war.

Zeile 161 :   attachedBlocks.replace(otherAgentName, blockToConnect);
attachedBlocks tracked nur die eigenen Blocks und die Keys sind die koordinaten.toString() für andere Agenten wird dort ja nichts getracked.

Die implementierung des Senden und Empfangens der Nachrichten fehlt.

**Comment by alimakW** [comment]
Ich habe neue Version heute gepusht.

**Comment by kaimuell** [comment]
Code Review 25.07.

Warum ist das AttachedBlocksModule jetzt ein Agent und im Scheduler als ein solcher eingetragen?

Sonst sieht es soweit funktional aus, wenn Nachrichten verschickt und verarbeitet werden. Ohne Tests aber noch nicht genau zu sagen.
Statt die Nachrichten zu broadcasten sollten sie besser genau an den von der Action betroffenen Agenten geschickt werden. schliesslich wird ja auch nur an diesen attached / detached. 

Integer.parseInt(((Identifier) ((ParameterList) lastAction.getParameters().get(1)).get(1)).toProlog());
sollte theoretisch funktionieren. Sicherer und effektiver sollte aber sein, wenn man weiss das etwas eine Zahl ist, es zu einem Numeral zu casten :
((Numeral) percept).getValue().intValue()

**Comment by kaimuell** [comment]
Connect Actions werden Funktional erkannt.
