### ISSUE TITLE
Agent-brain

### ISSUE THREAD

**Issue by julz-hub** [ss22-fp-mapc-gruppe6/agent#46]
- https://www.jooq.org/
- [SQLite](https://www.sqlite.org/)
- add all actions

**Comment by mpnsk** [comment]
ich bin mal das setup von jooq durchgegangen
https://github.com/ss22-fp-mapc-gruppe6/agent/commits/jooq-setup

er generiert mit `mvn compile` oder explizit mit `mvn -pl javaagents jooq-codegen:generate` aus jeder Tabelle in sqlite dann eine Klasse die als Datentyp für die Spalten herhält. Das ist dann das Argument im select-from-where für die Typsicherheit.

Anscheinend kann jooq neuerdings auch DAOs generieren und wenn wir unsere Klassen mit JPA-Annotationen zukleistern auch direkt umwandeln.

Das einzige was es nicht macht is der umgekehrte Weg aus Java-Klassen Tabellen zu schustern. Und es commited auch nicht automatisch in die Datenbank, jeder save muss explizit gemacht werden, wofür ich eigentlich sehr dankbar bin.
