### ISSUE TITLE
Wegfindung

### ISSUE THREAD

**Issue by kaimuell** [ss22-fp-mapc-gruppe6/agent#8]
Eventuell zuerst eine Minimierung über manhattan Distanz, (Ist als Methode in Point).

Später über A*

**Comment by mpnsk** [comment]
Agenten sollten nicht versuchen nicht-clearbare Objekte zu clearen (zB andere Agenten)

**Comment by mpnsk** [comment]
Todo: Sind Blöcke clearable? Blockieren Blöcke den Weg?
